blog/urls.py
from django.urls import path, re_path 
from . import views
from shop.views import ajaxviews

app_name = 'blog'
urlpatterns = [
    # All Blog Path <----->
    path('', views.all_blog, name = 'allblog_page'),
    # Single Blog Path <----->
    path('singel/<slug:slug>/', views.single_blog, name = 'single_blog_page'),
    # add comment
    path('ajax/add-comment/', ajaxviews.add_new_comment, name = 'add_new_comment'),
]

mouse_keyboard_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    url(r'^api/', include('rest_framework.urls', namespace = 'api_rest_framework')),
    path('oauth/', include('oauth2_provider.urls', namespace = 'oauth2_provider')),
]
urlpatterns += static(settings.STATIC_URL,document_root =  settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root =  settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import views, ajaxviews, singviews

app_name = 'shop'
urlpatterns = [
    # path('add-products-to-db/', views.add_products_to_db, name = 'add_products_to_db'),
    # Robot Path <----->
    url(r'^robots\.txt/$', TemplateView.as_view(template_name = "robots.txt", content_type = 'text/plain')),
    # Index Path <----->
    path('', views.index, name = 'index_page'),
    # Session Path <----->
    path('set-session', ajaxviews.set_session, name = 'set_session'),
    # About us Path <----->
    path('about-us/', views.about_us, name = 'about_us_page'),
    # Contact us Path <----->
    path('contact-us/', views.contact_us, name = 'contact_us_page'),
    # Sing in Path <----->
    path('signin/', views.sign_in, name = 'sign_in_page'),
    # Sing up Path <----->
    path('signup/', views.sign_up, name = 'sign_up_page'),
    # Search Path <----->
    path('serach/', views.search, name = 'search_page'),
    # Singel Product Path <----->
    path('products/<int:id>', views.singel_product, name = 'single_product'),
    # Show Card Path <----->
    path('card/', views.show_cart, name = 'show_card'),
    # Check Mobile Number <----->
    path('ajax/check/mobile-number/', singviews.check_mobilenubmer, name = 'ajax_check_mobilenumber'),
    # Sing in fun <----->
    path('ajax/singin/', singviews.singin, name = 'ajax_singin'),
    # Sing out fun <----->
    path('singout/', singviews.signout, name = 'singout'),
    # Sing in fun <----->
    path('ajax/singup/', singviews.singup, name = 'ajax_singup'),
    # Add to card fun <----->
    path('ajax/add-to-card/', ajaxviews.add_to_card, name = 'ajax_add_to_card'),
    # Update Factor fun <----->
    path('ajax/update-factor/', ajaxviews.update_factor, name = 'ajax_update_factor'),
    # <====================================================================================>
    # Add To Newsletters Path <----->
    path('add/new-email/', ajaxviews.add_to_newsletters, name = 'add_to_newsletters'),
    # add new connect us api <----->
    path('add/connesct-us/', ajaxviews.add_new_connectus , name = 'create_new_connectus_api'),
]

templates/parents/footer.html
{% load i18n static %}
	<!-- Footer -->
	<footer class="bg6 p-t-45 p-b-43 p-l-45 p-r-45">
		<div class="flex-w p-b-90">
			<div class="w-size6 p-t-30 p-l-15 p-r-15 respon3">
				<h4 class="s-text12 p-b-30">
					در تماس باشید
				</h4>

				<div>
					<p class="s-text7 w-size27">
						هفت روز هفته ، ۲۴ ساعت شبانه‌روز پاسخگوی شما هستیم
					</p>
				</div>
			</div>

			<div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
				<h4 class="s-text12 p-b-30">
					دسته بندی محصولات
				</h4>

				<ul>
					<li class="p-b-9">
						<a href="{% url "shop:search_page" %}" class="s-text7">
							موس
						</a>
					</li>

					<li class="p-b-9">
						<a href="{% url "shop:search_page" %}" class="s-text7">
							کیبورد
						</a>
					</li>
				</ul>
			</div>

			<div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
				<h4 class="s-text12 p-b-30">
					بخش ها
				</h4>

				<ul>
					<li class="p-b-9">
						<a href="/blog/">
							بلاگ
						</a>
					</li>


					<li class="p-b-9">
						<a href="/about-us/" class="s-text7">
							در باره ما
						</a>
					</li>

					<li class="p-b-9">
						<a href="#" class="s-text7">
							تماس با ما
						</a>
					</li>
				</ul>
			</div>

			<!-- <div class="w-size7 p-t-30 p-l-15 p-r-15 respon4">
				<h4 class="s-text12 p-b-30">
					کمک
				</h4>

				<ul>
					<li class="p-b-9">
						<a href="#" class="s-text7">
							Track Order
						</a>
					</li>

					<li class="p-b-9">
						<a href="#" class="s-text7">
							Returns
						</a>
					</li>

					<li class="p-b-9">
						<a href="#" class="s-text7">
							Shipping
						</a>
					</li>

					<li class="p-b-9">
						<a href="#" class="s-text7">
							FAQs
						</a>
					</li>
				</ul>
			</div> -->

			<div class="w-size8 p-t-30 p-l-15 p-r-15 respon3">
				<h4 class="s-text12 p-b-30">
					خبرنامه
				</h4>

				<form>
					{% csrf_token %}
					<div class="effect1 w-size9">
						<input class="s-text7 bg6 w-full p-b-5" type="email" name="email" id="input_email" placeholder="email@example.com">
						<span class="effect1-line"></span>
					</div>

					<div class="w-size2 p-t-20">
						<!-- Button -->
						<a class="flex-c-m size2 bg4 bo-rad-23 hov1 m-text3 trans-0-4">
							<span id="add-new-email">عضویت</span>
						</a>
					</div>
				</form>
			</div>
		</div>

		<div class="t-center p-l-15 p-r-15">
			<div class="t-center s-text8 p-t-20">
				.می‌باشد keymou کلیه حقوق این سایت متعلق به</div>
		</div>
	</footer>



	<!-- Back to top -->
	<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
	</div>

	<!-- Container Selection1 -->
	<div id="dropDownSelect1"></div>

	<!--===============================================================================================-->
		<script type="text/javascript" charset="utf-8" src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></script>
    <!--===============================================================================================-->
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
    <!--===============================================================================================-->
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
    <!--===============================================================================================-->
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/slick/slick.min.js" %}"></script>
        <script type="text/javascript" charset="utf-8" src="{% static "js/slick-custom.js" %}"></script>
    <!--===============================================================================================-->
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
    <!--===============================================================================================-->
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/lightbox2/js/lightbox.min.js" %}"></script>
    <!--===============================================================================================-->
        <script type="text/javascript" charset="utf-8" src="{% static "vendor/sweetalert/sweetalert.min.js" %}"></script>
    <!--===============================================================================================-->
		<script type="text/javascript" charset="utf-8" src="{% static "js/main.js" %}"></script>
	<!--===============================================================================================-->
		<script type="text/javascript" charset="utf-8" src="{% static "vendor/select2/select2.min.js" %}"></script>
	<!--===============================================================================================-->
		<script text="javascripts">
			$("#add-new-email").on("click", function (e) {
			var  this_email = $('#input_email').val();
			
			$.ajax(
				{
				type: 'POST',
				url: '{% url "shop:add_to_newsletters" %}',
				data: {
					email: this_email,
					csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
				},
				success: function (json) {
					if (json.message == '201') {
						alert('شما با موفقیت در خبرنامه عضو شدید.');
					}
					else if (json.message == '200') {
						alert('شما قبلا در خبرنامه عضو شدید!');
					}	
				},
				error: function (xhr) {
					alert(xhr.status + ": " + xhr.responseText);
				}
				}
			);      
			});
		</script>
	<!--===============================================================================================-->
	<script charset="utf-8" src="{% static "js/main.js" %}"></script>

templates/parents/head.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
		<link rel="icon" type="image/png" href="{% static "img/icons/favicon.png" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" href="{% static "css/all.min.css" %}" />
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "fonts/themify/themify-icons.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "fonts/elegant-font/html-css/style.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/slick/slick.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/lightbox2/css/lightbox.min.css" %}">
	<!--===============================================================================================-->
		<link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
	<!--===============================================================================================-->
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
	<!--===============================================================================================-->
	<!--set session-->
	{% if not request.user.is_authenticated %}
		<script text="javascripts">
			$('document').ready(function() {
				var this_page_path = '{{request.path|safe}}';
				$.ajax(
					{
						type: 'POST',
						url: '{% url "shop:set_session" %}',
						data :{
							this_path:this_page_path,
							csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
						},
						success: function (json) {
							if (json.status == true){
								console.log(json.status);
							}
						},
						error: function (xhr) {
							console.log(xhr.status + ": " + xhr.responseText);
						}
					}
				);      
			});
		</script>
	{% endif %}

templates/parents/header-section.html
{% load i18n static %}
<body class="animsition">
	<!-- Header -->
	<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="wrap_header">
				<!-- Logo -->
				<!-- <a href="index.html" class="logo">
					<img src="../static/img/icons/logo_new_2__2x.png" alt="IMG-LOGO">
				</a> -->

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="{% url "shop:contact_us_page" %}">تماس با ما</a>
							</li>

							<li>
								<a href="{% url "shop:about_us_page" %}">درباره ما</a>
							</li>

							<li>
								<a href="{% url "blog:allblog_page" %}">بلاگ</a>
							</li>

							<li class="sale-noti">
								<a href="/">خانه</a>
								<!-- <ul class="sub_menu">
									<li><a href="index.html">Homepage V1</a></li>
									<li><a href="home-02.html">Homepage V2</a></li>
									<li><a href="home-03.html">Homepage V3</a></li>
								</ul> -->
							</li>
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->
				<div class="header-icons">
					<a {% if not request.user.is_authenticated %}href="/signin/"{% else %}href="/singout/"{% endif %} class="header-wrapicon1 dis-block" id="user-account">
						<img {% if not request.user.is_authenticated %}src="../static/img/icons/icon-header-01.png"{% else %}src="{{request.user.profile.url}}"{% endif %} class="header-icon1 {% if request.user.is_authenticated %}profileimg{% endif %}" alt="ICON">
					</a>
					<!-- {% if request.user.is_authenticated %}
						<ul class="sub-menu" id="header-menu">
							<li><a href="index.html">Homepage V1</a></li>
							<li><a href="home-02.html">Homepage V2</a></li>
							<li><a href="home-03.html">Homepage V3</a></li>
						</ul>
					{% endif %} -->

					{% if request.user.is_authenticated %}
						<span class="linedivide1"></span>

						<div class="header-wrapicon2">
							<a href="{% url "shop:show_card" %}">
								<img src="{% static "img/icons/icon-header-02.png" %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
							</a>
						</div>
					{% endif %}
				</div>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="index.html" class="logo-mobile">
				<img src="../static/img/icons/logo.png" alt="IMG-LOGO">
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="../static/img/icons/icon-header-01.png" class="header-icon1" alt="ICON">
					</a>

					{% if request.user.is_authenticated %}
						<span class="linedivide2"></span>

						<div class="header-wrapicon2">
							<a href="{% url "shop:show_card" %}">
								<img src="{% static "img/icons/icon-header-02.png" %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
							</a>
						</div>
					{% endif %}
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over $100
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								fashe@example.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>USD</option>
									<option>EUR</option>
								</select>
							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="index.html">Home</a>
						<ul class="sub-menu">
							<li><a href="index.html">Homepage V1</a></li>
							<li><a href="home-02.html">Homepage V2</a></li>
							<li><a href="home-03.html">Homepage V3</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>

					<li class="item-menu-mobile">
						<a href="product.html">Shop</a>
					</li>

					<li class="item-menu-mobile">
						<a href="product.html">Sale</a>
					</li>

					<li class="item-menu-mobile">
						<a href="cart.html">Features</a>
					</li>

					<li class="item-menu-mobile">
						<a href="blog.html">Blog</a>
					</li>

					<li class="item-menu-mobile">
						<a href="about.html">About</a>
					</li>

					<li class="item-menu-mobile">
						<a href="contact.html">Contact</a>
					</li>
				</ul>
			</nav>
		</div>
	</header>