blog/urls.py
from django.urls import path, re_path 
from . import views
from shop.views import ajaxviews

app_name = 'blog'
urlpatterns = [
    # All Blog Path <----->
    path('', views.all_blog, name = 'allblog_page'),
    # Single Blog Path <----->
    path('singel/<slug:slug>/', views.single_blog, name = 'single_blog_page'),
    # add comment
    path('ajax/add-comment/', ajaxviews.add_new_comment, name = 'add_new_comment'),
]

mouse_keyboard_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    url(r'^api/', include('rest_framework.urls', namespace = 'api_rest_framework')),
    path('oauth/', include('oauth2_provider.urls', namespace = 'oauth2_provider')),
]
urlpatterns += static(settings.STATIC_URL,document_root =  settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root =  settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import views, ajaxviews, singviews

app_name = 'shop'
urlpatterns = [
    # path('add-products-to-db/', views.add_products_to_db, name = 'add_products_to_db'),
    # Robot Path <----->
    url(r'^robots\.txt/$', TemplateView.as_view(template_name = "robots.txt", content_type = 'text/plain')),
    # Index Path <----->
    path('', views.index, name = 'index_page'),
    # Session Path <----->
    path('set-session', ajaxviews.set_session, name = 'set_session'),
    # About us Path <----->
    path('about-us/', views.about_us, name = 'about_us_page'),
    # Contact us Path <----->
    path('contact-us/', views.contact_us, name = 'contact_us_page'),
    # Sing in Path <----->
    path('signin/', views.sign_in, name = 'sign_in_page'),
    # Sing up Path <----->
    path('signup/', views.sign_up, name = 'sign_up_page'),
    # Search Path <----->
    path('serach/', views.search, name = 'search_page'),
    # Singel Product Path <----->
    path('products/<int:id>', views.singel_product, name = 'single_product'),
    # Show Card Path <----->
    path('card/', views.show_cart, name = 'show_card'),
    # Check Mobile Number <----->
    path('ajax/check/mobile-number/', singviews.check_mobilenubmer, name = 'ajax_check_mobilenumber'),
    # Sing in fun <----->
    path('ajax/singin/', singviews.singin, name = 'ajax_singin'),
    # Sing out fun <----->
    path('singout/', singviews.signout, name = 'singout'),
    # Sing in fun <----->
    path('ajax/singup/', singviews.singup, name = 'ajax_singup'),
    # Add to card fun <----->
    path('ajax/add-to-card/', ajaxviews.add_to_card, name = 'ajax_add_to_card'),
    # Update Factor fun <----->
    path('ajax/update-factor/', ajaxviews.update_factor, name = 'ajax_update_factor'),
    # <====================================================================================>
    # Add To Newsletters Path <----->
    path('add/new-email/', ajaxviews.add_to_newsletters, name = 'add_to_newsletters'),
    # add new connect us api <----->
    path('add/connesct-us/', ajaxviews.add_new_connectus , name = 'create_new_connectus_api'),
]

blog/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.db.models import JSONField
from datetime import datetime
from django.shortcuts import reverse

# --------------------------------------------------------------------------------------------------------------------------------------

# Blog (بلاگ) Model
class Blog(models.Model): 
    title = models.CharField(verbose_name = 'عنوان', max_length = 255)
    slug = models.SlugField(verbose_name = 'شناسه')
    summary = models.CharField(verbose_name = 'خلاصه', max_length = 300)
    author = models.CharField(verbose_name = 'نویسنده', max_length = 450, null = True, blank = True)
    code = models.TextField(verbose_name = 'کد HTML')
    top_image = models.ImageField(verbose_name = 'عکس شاخص', upload_to = 'media/images/blog/')
    slider = models.ImageField(verbose_name = 'اسلایدر', upload_to = 'media/images/blog/slider/')
    reted_list = JSONField(verbose_name = 'لیست امتیاز', null = True, blank = True)
    liked_list = JSONField(verbose_name = 'لیست لایک', null = True, blank = True)
    datecreate = models.DateTimeField(verbose_name = 'تاریخ بارگذاری', auto_now_add = True)
    dtatupdate = models.DateTimeField(verbose_name = 'تاریخ بروزرسانی', auto_now = True)
    PUBLISH_STATUS = (
        (True,'منتشر شده'),
        (False,'منتشر نشده'),
    )
    publish = models.BooleanField(verbose_name = 'وضعیت', choices = PUBLISH_STATUS, default = False)

    def __str__(self):
        return "{}".format(self.title)

    def get_url(self):
        return reverse("blog:single_blog_page", kwargs = {
            'slug': self.slug,
        })

    def save_comment(self, name, message):
        if self.reted_list is not None:
            this_comment = {'name': name, 'message': message}
            this_list = list(self.reted_list['list'])
            this_list.append(this_comment)
            self.reted_list['list'] = this_list
            self.save()
        else:
            self.reted_list = {'list': []}
            this_comment = {'name': name, 'message': message}
            self.reted_list['list'] = this_comment
            self.save()


    class Meta:
        ordering = ('id',)   
        verbose_name = "بلاگ"
        verbose_name_plural = "بلاگ ها"
    
#----------------------------------------------------------------------------------------------------------------------------------------

blog/views.py
from django.shortcuts import render
from .models import Blog
from shop.models import Slider
from django.core.paginator import Paginator
from django.db.models import Q


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

def all_blog(request, words = None):
    if request.method != 'POST':
        # get slider
        slider = Slider.objects.filter(position = '4').latest('datecreate')
        # get blog post
        post_list = Blog.objects.filter(publish = True).order_by('-datecreate')
        # post paginator
        paginator = Paginator(post_list, 2)
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)
    
        context = {
            'Slider' : slider,
            'PostList' : posts,
        }

        return render(request, 'blog/index.html', context)
    else:
        words = request.POST["search"]
        # search word
        words = words.split(' ')
        words = list(filter(lambda i: i!='', words))
        search_words = []
        for word in words:
            search_word = list(map(lambda x: x + '\s*', word.replace(' ','')[:-1]))
            search_word = ''.join(search_word) + word[-1]
            search_words.append(search_word)
        search_word = r'.*'.join(search_words)
        # get slider
        slider = Slider.objects.filter(position = '4').latest('datecreate')
        # get blog post
        post_list = Blog.objects.filter(publish = True, title__regex = search_word).order_by('-datecreate')
        # post paginator
        paginator = Paginator(post_list, 2)
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)
    
        context = {
            'Slider' : slider,
            'PostList' : posts,
        }

        return render(request, 'blog/index.html', context)

def single_blog(request, slug):
    # get blog post
    this_post = Blog.objects.get(slug = slug)
 
    context = {
        'This_post' : this_post,
    }

    return render(request, 'blog/blog-details.html', context)

templates/blog/blog-details.html
{% load i18n static %}

{% block headtag %}
	{% include "parents/head.html" %}
{% endblock %}


<title>Blog | {{This_post.title}}</title>
</head>

{% block header %}
	{% include "parents/header-section.html" %}
{% endblock %}

<!-- breadcrumb -->
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
	<a href="{% url "shop:index_page"%}" class="s-text16">
		خانه
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>

	<a href="{% url "blog:allblog_page"%}" class="s-text16">
		وبلاگ
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>

	<span class="s-text17">
		{{This_post.title}}
	</span>
</div>

<!-- content page -->
<section class="bgwhite p-t-60 p-b-25">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-lg-12 p-b-80">
				<div class="p-r-50 p-r-0-lg">
					<div class="p-b-40">
						<div class="blog-detail-img wrap-pic-w">
							<img src="{{This_post.slider.url}}" alt="IMG-BLOG">
						</div>

						<div class="blog-detail-txt p-t-33" style="direction: rtl;">
							<h4 class="p-b-11 m-text24">
								{{This_post.title}}
							</h4>

							<div class="s-text8 flex-w flex-m p-b-21">
								<span>
									{{This_post.author}}
									<span class="m-l-3 m-r-6">|</span>
								</span>

								<span>
									{{This_post.datecreate.date}}
									<span class="m-l-3 m-r-6">|</span>
								</span>

								<span>
									نظرات {{This_post.reted_list.list|length}} 
								</span>
							</div>

							<p class="p-b-25">
								{% autoescape off %}{{This_post.code}}{% endautoescape %}
							</p>
						</div>
					</div>

					<!-- Leave a comment -->
					<form class="leave-comment" style="direction: rtl;">
						{% csrf_token %}
						<h4 class="m-text25 p-b-14">
							نظر بدهید.
						</h4>

						<p class="s-text8 p-b-40">
							آدرس ایمیل شما مخفی خواهد ماند.
						</p>

						<div class="bo12 of-hidden size19 m-b-20">
							<input class="sizefull s-text7 p-l-18 p-r-18" type="text" name="name" placeholder="نام" id="input_username">
						</div>

						<textarea class="dis-block s-text7 size18 bo12 p-l-18 p-r-18 p-t-13 m-b-20" name="comment" placeholder="نظر..." id="input_message"></textarea>

						<div class="w-size24">
							<!-- Button -->
							<button class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4" type="submit" id="send-form">
								ارسال
							</button>
						</div>
					</form>
				</div>
			</div>

		
		</div>
	</div>
</section>


<!-- Footer -->
{% block footer %}
	{% include "parents/footer.html" %}
{% endblock %}

<!-- Ajax -->
<script text="javascripts">
	$("#send-form").on("click", function (e) {
		var  this_id = '{{This_post.id|safe}}';
		var  thisuser_name = $('#input_username').val();
		var  thisuser_message = $('#input_message').val();
		console.log(thisuser_name);
		console.log(thisuser_message);
		if ((thisuser_name != '') && (thisuser_message != '	')){
			$.ajax(
				{
					type: 'POST',
					url: '{% url "blog:add_new_comment" %}',
					data: {
						this_post: this_id,
						this_fullname: thisuser_name,
						this_message: thisuser_message,
						csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
					},
					success: function (json, status, xhr) {
						if (xhr.status == 201) {
							alert('نظر شما ثبت شد.');
						}
					},
					error: function (xhr) {
						alert('خطایی رخ داده است.');
						console.log(xhr.status + ": " + xhr.responseText);
					}
				}
			);  
		}
		else{
			alert('نام و پیام اجباریست!');
		}
	})
</script>



<!--===============================================================================================-->
	<script type="text/javascript" charset="utf-8" src="{% static "vendor/select2/select2.min.js" %}"></script>
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->

</body>
</html>

templates/blog/index.html
{% load i18n static %}

{% block headtag %}
	{% include "parents/head.html" %}
{% endblock %}

<title>Blog</title>
</head>

{% block header %}
	{% include "parents/header-section.html" %}
{% endblock %}

<!-- Title Page -->
<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url({{Slider.image.url}});"></section>

<!-- content page -->
<section class="bgwhite p-t-60">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-lg-9 p-b-75">
				<div class="p-r-50 p-r-0-lg">
					<!-- item blog -->
					{% for item in PostList %}
						<div class="item-blog p-b-80">
							<a href="{{item.get_url}}" class="item-blog-img pos-relative dis-block hov-img-zoom">
								<img src="{{item.slider.url}}" alt="IMG-BLOG">

								<span class="item-blog-date dis-block flex-c-m pos1 size17 bg4 s-text1">
									{{item.datecreate.date}}
								</span>
							</a>

							<div class="item-blog-txt p-t-33">
								<h4 class="p-b-11">
									<a href="{{item.get_url}}" class="m-text24">
										{{item.title}}
									</a>
								</h4>

								<div class="s-text8 flex-w flex-m p-b-21">
									<span>
										{{item.author}}
										<!-- <span class="m-l-3 m-r-6">|</span> -->
									</span>

									<!-- <span>
										موس های جدید
										<span class="m-l-3 m-r-6">|</span>
									</span> -->

									<!-- <span>
										8 Comments
									</span> -->
								</div>

								<p class="p-b-12">
									{{item.summary}}
								</p>

								<a href="{{item.get_url}}" class="s-text20">
									بیشتر بخوانید
									<i class="fa fa-long-arrow-right m-l-8" aria-hidden="true"></i>
								</a>
							</div>
						</div>
					{% endfor %}
				</div>

				<!-- Pagination -->
				<div class="pagination flex-m flex-w p-r-50">
					{% if PostList.has_previous %}
						<a href="?page=1" class="item-pagination flex-c-m trans-0-4">اولی</a>
						<a href="?page={{ PostList.previous_page_number }}" class="item-pagination flex-c-m trans-0-4">قبلی</a>
					{% endif %}
			
					<span class="item-pagination flex-c-m trans-0-4 active-pagination" >
						{{ PostList.number }}
					</span>
			
					{% if PostList.has_next %}
						<a href="?page={{ PostList.next_page_number }}" class="item-pagination flex-c-m trans-0-4">بعدی</a>
						<a href="?page={{ PostList.paginator.num_pages }}" class="item-pagination flex-c-m trans-0-4">آخری</a>
					{% endif %}
				</div>
			</div>

			<div class="col-md-4 col-lg-3 p-b-75">
				<div class="rightbar">
					<!-- Search -->
					
					<div class="pos-relative bo11 of-hidden">
						<form class="leave-comment" style="direction: rtl;" method="POST" action="{% url "blog:allblog_page" %}">
							{% csrf_token %}
							<input class="s-text7 size16 p-l-23 p-r-50" type="text" name="search" placeholder="جستجو" id="search">

							<button class="flex-c-m size5 ab-r-m color1 color0-hov trans-0-4" type="submit">
								<i class="fs-13 fa fa-search" aria-hidden="true"></i>
							</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% block footer %}
	{% include "parents/footer.html" %}
{% endblock %}

<!--===============================================================================================-->
	<script type="text/javascript" src="../static/vendor/select2/select2.min.js"></script>
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});

		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect2')
		});
	</script>
<!--===============================================================================================-->
</body>
</html>