blog/urls.py
from django.urls import path, re_path 
from . import views
from shop.views import ajaxviews

app_name = 'blog'
urlpatterns = [
    # All Blog Path <----->
    path('', views.all_blog, name = 'allblog_page'),
    # Single Blog Path <----->
    path('singel/<slug:slug>/', views.single_blog, name = 'single_blog_page'),
    # add comment
    path('ajax/add-comment/', ajaxviews.add_new_comment, name = 'add_new_comment'),
]

mouse_keyboard_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace = 'shop')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    url(r'^api/', include('rest_framework.urls', namespace = 'api_rest_framework')),
    path('oauth/', include('oauth2_provider.urls', namespace = 'oauth2_provider')),
]
urlpatterns += static(settings.STATIC_URL,document_root =  settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root =  settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import views, ajaxviews, singviews

app_name = 'shop'
urlpatterns = [
    # path('add-products-to-db/', views.add_products_to_db, name = 'add_products_to_db'),
    # Robot Path <----->
    url(r'^robots\.txt/$', TemplateView.as_view(template_name = "robots.txt", content_type = 'text/plain')),
    # Index Path <----->
    path('', views.index, name = 'index_page'),
    # Session Path <----->
    path('set-session', ajaxviews.set_session, name = 'set_session'),
    # About us Path <----->
    path('about-us/', views.about_us, name = 'about_us_page'),
    # Contact us Path <----->
    path('contact-us/', views.contact_us, name = 'contact_us_page'),
    # Sing in Path <----->
    path('signin/', views.sign_in, name = 'sign_in_page'),
    # Sing up Path <----->
    path('signup/', views.sign_up, name = 'sign_up_page'),
    # Search Path <----->
    path('serach/', views.search, name = 'search_page'),
    # Singel Product Path <----->
    path('products/<int:id>', views.singel_product, name = 'single_product'),
    # Show Card Path <----->
    path('card/', views.show_cart, name = 'show_card'),
    # Check Mobile Number <----->
    path('ajax/check/mobile-number/', singviews.check_mobilenubmer, name = 'ajax_check_mobilenumber'),
    # Sing in fun <----->
    path('ajax/singin/', singviews.singin, name = 'ajax_singin'),
    # Sing out fun <----->
    path('singout/', singviews.signout, name = 'singout'),
    # Sing in fun <----->
    path('ajax/singup/', singviews.singup, name = 'ajax_singup'),
    # Add to card fun <----->
    path('ajax/add-to-card/', ajaxviews.add_to_card, name = 'ajax_add_to_card'),
    # Update Factor fun <----->
    path('ajax/update-factor/', ajaxviews.update_factor, name = 'ajax_update_factor'),
    # <====================================================================================>
    # Add To Newsletters Path <----->
    path('add/new-email/', ajaxviews.add_to_newsletters, name = 'add_to_newsletters'),
    # add new connect us api <----->
    path('add/connesct-us/', ajaxviews.add_new_connectus , name = 'create_new_connectus_api'),
]

shop/views.py
from django.shortcuts import render
from .models import Product, Slider
from blog.models import Blog
import json, random


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# get random product list
def get_random_product_list():
    product_list = list(Product.objects.filter(publish = True))
    result = []
    count = len(product_list)

    while (count != 0) and (len(result) != 6):
        random_item = random.randint(0, (count - 1))
        result.append(product_list[random_item])
        product_list.remove(product_list[random_item])
        count -= 1

    return result

# get random disproduct list
def get_random_disproduct_list():
    product_list = list(Product.objects.filter(discount__gt = 0, publish = True))
    result = []
    count = len(product_list)

    while (count != 0) and (len(result) != 8):
        random_item = random.randint(0, (count - 1))
        result.append(product_list[random_item])
        product_list.remove(product_list[random_item])
        count -= 1

    return result

def index(request):
    # get random products
    random_products = get_random_product_list()
    # get top products
    top_products = get_random_disproduct_list()
    # get sliders
    sliders = Slider.objects.filter(position = 0, publish = True)
    # get ads banner
    ads_banner = Slider.objects.filter(position = 1, publish = True)
    # get blog post
    blog_posts = Blog.objects.filter(publish = True).order_by('-datecreate')[:3]
 
    context = {
        'Random_Products' : random_products,
        'Top_Products' : top_products,
        'AdsBanner' : ads_banner,
        'BlogList' : blog_posts,
        'Sliders' : sliders,
    }

    return render(request, 'shop/index.html', context)


def about_us(request):
    # get sliders
    top_slider = Slider.objects.get(position = 2, publish = True)

    context = {
        'Slider' : top_slider,
    }

    return render(request, 'shop/about.html', context)


def contact_us(request):
    # get sliders
    # top_slider = Slider.objects.get(position = 2, publish = True)

    context = {
        # 'Slider' : top_slider,
    }

    return render(request, 'shop/contact.html', context)


def sign_in(request):

    return render(request, 'registration/signin.html')


def sign_up(request):

    return render(request, 'registration/signup.html')


# # add products to db
# def add_products_to_db(request):

#     # read json file
#     with open("mouse_keyboard_store/data_keyboards.json", encoding = 'utf8') as data:
#         this_file = json.load(data)
#     # add data to db
#     print(str(len(this_file)))
#     for item in this_file:
#         this_title = item['title']
#         this_description = item['description']
#         this_image_list = item['ImagesUrl']
#         this_top_image = this_image_list[0]
#         this_image_list.remove(this_top_image)
#         this_point = float(item['point'])
#         this_price = ''.join(item['price'].split(','))
#         this_attributes = item['Params']
#         # this product
#         this_product = Product.objects.create(title = this_title, description = this_description, point = this_point, price = this_price, top_image = this_top_image, publish = True)
#         # set image list
#         this_product.image_list = this_image_list
#         this_product.save()
#         # set attributes
#         this_product.save_attributes(this_attributes)
#         print(str(len(this_file) - 1))

#     return render(request, 'shop/about.html')

shop/views/ajaxviews.py
from rest_framework.decorators import api_view, permission_classes
from django.utils.datastructures import MultiValueDictKeyError
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail, EmailMultiAlternatives
from django.contrib.sessions.models import Session
from rest_framework.response import Response
from django.shortcuts import redirect
from django.http import JsonResponse
from django.utils import timezone
from django.conf import settings
from rest_framework.status import (
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_403_FORBIDDEN,
    HTTP_200_OK,
    HTTP_201_CREATED,
    HTTP_202_ACCEPTED,
    HTTP_500_INTERNAL_SERVER_ERROR,
)
# from .serializers import *
from kavenegar import *
import threading, random, string, datetime

# get model
from shop.models import OptionMeta, Contactus, Factor, FactorPost, Product
from blog.models import Blog

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# add to newsletters //req : get email form request //result: ({'status' : (True, False), 'message' : msg}) OR error
@csrf_exempt
@api_view(["POST"])
@permission_classes([AllowAny])
def add_to_newsletters(request):
    try:
        # get data
        this_email = request.POST.get("email")
        # check newsletters list
        if OptionMeta.objects.filter(title = 'newsletters').exists():
            newsletters_list = OptionMeta.objects.get(title = 'newsletters')
        else:
            newsletters_list = OptionMeta.objects.create(title = 'newsletters', content = {'email_list' : []})
        # check email status
        if this_email in newsletters_list.content['email_list']:
            return JsonResponse({'status' : True, 'message' : '200'} , status = HTTP_200_OK)
        else:
            # add new email
            newsletters_list.content['email_list'].append(this_email)
            newsletters_list.save()
            # send new email
            # subject, from_email, to = 'عضویت در خبرنامه سایت keymou', 'info@keymou.ir', this_email
            # text_content = 'عضویت شما در خبرنامه keymou تبریک می گوییم!'
            # html_content = '<h1 style="text-align: center;"><img src="https://s16.picofile.com/file/8413396668/logo_menu_navbar.pngy" alt="logo" width="161" height="69" /></h1> <h2 style="text-align: right;"><span style="color: #333399;">شما با موفقیت در خبرنامه سایت ما&nbsp;</span><span style="color: #333399;"><span style="color: #333399;">عضو شدید، از این بابت بسیار خرسندیم.</span></span></h2> <h3 style="text-align: right;"><span style="color: #000000;">با عضویت در این خبرنامه می توانید از&nbsp;</span></h3> <ul style="text-align: right;"> <li style="padding-left: 30px;"><span style="color: #000080;">جدید ترین محصولات</span></li> <li style="padding-left: 30px;"><span style="color: #000080;">جدید ترین مطالب وبلاگ</span></li> <li style="padding-left: 30px;"><span style="color: #000080;">جدید ترین تخفیفات سایت</span></li> </ul> <p style="text-align: right;"><span style="color: #000000;">در سریع ترین زمان با خبر شود.</span></p> <p style="text-align: left;"><a title="آدرس سایت ما" href="https://keymou.ir/" target="_blank" rel="noopener">keymou.ir</a></p>'
            # msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            # msg.attach_alternative(html_content, "text/html")
            # msg.send()

            return JsonResponse({'status' : True, 'message' : '201'} , status = HTTP_201_CREATED)
    except Exception as e:
        return JsonResponse({'status' : False, 'message' : str(e)}, status = HTTP_500_INTERNAL_SERVER_ERROR)


# set session
def set_session(request):
    response_data = {}
    try:
        this_path = request.POST['this_path']
        # get path other than non-account path 
        if not ((this_path == '/signin/') or (this_path == '/signup/') or (this_path == '/forgotpassword/')):
            request.session['next'] = this_path
        response_data['status'] = True
        return JsonResponse(response_data)
    except Exception as e:
        response_data['status'] = False
        response_data['message'] = str(e)
        return JsonResponse(response_data)


# add connect us
@csrf_exempt
@api_view(["POST"])
@permission_classes([AllowAny])
def add_new_connectus(request):
    try:
        # get data
        this_name = request.POST.get("this_fullname")
        this_mobile = request.POST.get("this_mobile")
        this_email = request.POST.get("this_email")
        this_message = request.POST.get("this_message")
        # check data
        if (len(this_name) > 0) and ((len(this_mobile) > 0) or (len(this_email) > 0)) and (len(this_message) > 0):
            # create new connect us
            this_connectus = Contactus.objects.create(full_name = this_name, description = this_message)
            # check mobile
            if this_mobile != 'null':
                this_connectus.mobile = this_mobile
            # check email
            if this_email != 'null':
                this_connectus.email = this_email
            # save data
            this_connectus.save()

            return JsonResponse({'status' : True}, status = HTTP_201_CREATED)
        else:
            return JsonResponse({'status' : False, 'message' : 'Input data is incomplete'}, status = HTTP_400_BAD_REQUEST)
    except Exception as e:
        return JsonResponse({'status' : False, 'message' : str(e)}, status = HTTP_500_INTERNAL_SERVER_ERROR)


# add comment
@csrf_exempt
@api_view(["POST"])
@permission_classes([AllowAny])
def add_new_comment(request):
    try:
        # get data
        this_post_id = request.POST.get("this_post")
        this_name = request.POST.get("this_fullname")
        this_message = request.POST.get("this_message")
        # check data
        if (len(this_name) > 0) and (len(this_message) > 0):
            # get this post
            this_post = Blog.objects.get(id = this_post_id)
            # add comment
            this_post.save_comment(this_name, this_message)

            return JsonResponse({'status' : True}, status = HTTP_201_CREATED)
        else:
            return JsonResponse({'status' : False, 'message' : 'Input data is incomplete'}, status = HTTP_400_BAD_REQUEST)
    except Exception as e:
        return JsonResponse({'status' : False, 'message' : str(e)}, status = HTTP_500_INTERNAL_SERVER_ERROR)


# add to card
@csrf_exempt
@api_view(["POST"])
@permission_classes([IsAuthenticated])
def add_to_card(request):
    try:
        # get data
        this_product_id = request.POST.get("this_product")
        this_count = request.POST.get("this_count")
        # check data
        if len(this_count) > 0:
            # check factor
            if Factor.objects.filter(PaymentStatus = False, FK_User = request.user).exists():
                this_factor = Factor.objects.get(FK_User = request.user, PaymentStatus = False)
                # get this product
                this_product = Product.objects.get(id = this_product_id)
                if this_factor.FK_FactorPost.filter(FK_Product = this_product).exists():
                    this_item = this_factor.FK_FactorPost.get(FK_Product = this_product)
                    this_item.ProductCount += int(this_count)
                else:
                    this_item = FactorPost.objects.create(FK_Product = this_product, ProductCount = int(this_count))
                    Factor.objects.filter(PaymentStatus = False, FK_User = request.user)[0].FK_FactorPost.add(this_item)
            else:
                this_factor = Factor.objects.create(FK_User = request.user, PaymentStatus = False)
                this_product = Product.objects.get(id = this_product_id)
                this_item = FactorPost.objects.create(FK_Product = this_product, ProductCount = int(this_count))
                this_factor.FK_FactorPost.add(this_item)

            return JsonResponse({'status' : True}, status = HTTP_200_OK)
        else:
            return JsonResponse({'status' : False, 'message' : 'Input data is incomplete'}, status = HTTP_400_BAD_REQUEST)
    except Exception as e:
        return JsonResponse({'status' : False, 'message' : str(e)}, status = HTTP_500_INTERNAL_SERVER_ERROR)


# update_factor
@csrf_exempt
@api_view(["POST"])
@permission_classes([IsAuthenticated])
def update_factor(request):
    try:
        # get data
        this_phone = request.POST.get("this_phone")
        this_address = request.POST.get("this_address")
        this_zip = request.POST.get("this_zip")
        this_state = request.POST.get("this_state")
        this_city = request.POST.get("this_city")
        this_bigcity = request.POST.get("this_bigcity")
        # check data
        if (len(this_phone) > 0) and (len(this_address) > 0) and (len(this_zip) > 0) and (len(this_state) > 0) and (len(this_city) > 0) and (len(this_bigcity) > 0):
            # get this factor
            this_factor = Factor.objects.get(FK_User = request.user, PaymentStatus = False)
            this_factor.MobileNumber = this_phone
            this_factor.ZipCode = this_zip
            this_factor.Address = this_address
            this_factor.City = this_city
            this_factor.BigCity = this_bigcity
            this_factor.State = this_state
            total_price = 0
            for item in this_factor.FK_FactorPost.all():
                total_price += item.Endprice
            this_factor.TotalPrice = total_price
            this_factor.PaymentStatus = True
            this_factor.save()
   
            return JsonResponse({'status' : True}, status = HTTP_200_OK)
        else:
            return JsonResponse({'status' : False, 'message' : 'Input data is incomplete'}, status = HTTP_400_BAD_REQUEST)
    except Exception as e:

templates/shop/about.html
{% load i18n static %}

{% block headtag %}
	{% include "parents/head.html" %}
{% endblock %}

	<title>About us</title>
</head>

{% block header %}
	{% include "parents/header-section.html" %}
{% endblock %}

<!-- Title Page -->
<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url({{Slider.image.url}});">
	<!-- <h2 class="l-text2 t-center">
		درباره
	</h2> -->
</section>

<!-- content page -->
<section class="bgwhite p-t-66 p-b-38">
	<div class="container">
		<div class="row">
			<div class="col-md-4 p-b-30">
				<div class="hov-img-zoom">
					<img src="../static/img/banner-14.jpg" alt="IMG-ABOUT">
				</div>
			</div>

			<div class="col-md-8 p-b-30">
				<h3 class="m-text26 p-t-15 p-b-16">
					برند ما
				</h3>

				<p class="p-b-28">
					لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
				</p>
				<div class="bo13 p-l-29 m-l-9 p-b-10">
					<p class="p-b-11">
						خلاقیت فقط اتصال چیزهاست. وقتی از افراد خلاق می پرسید که چگونه کاری را انجام داده اند ، کمی احساس گناه می کنند زیرا واقعاً این کار را نکرده اند ، آنها فقط چیزی را دیده اند. بعد از مدتی برای آنها واضح به نظر می رسید.	
					</p>
					<span class="s-text7">
						- Steve Job’s
					</span>
				</div>
			</div>
		</div>
	</div>
</section>

{% block footer %}
	{% include "parents/footer.html" %}
{% endblock %}

</body>
</html>

templates/shop/product-details.html
{% load i18n static %}
{% load filters %}

{% block headtag %}
	{% include "parents/head.html" %}
{% endblock %}

	<title>Product | {{ThisProduct.title}}</title>
</head>

{% block header %}
	{% include "parents/header-section.html" %}
{% endblock %}

<!-- breadcrumb -->
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
	<a href="{% url "shop:index_page"%}" class="s-text16">
		خانه
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>

	<a href="#" class="s-text16">
		محصولات
		<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
	</a>
	
	<span class="s-text17">
		{{ThisProduct.title}}
	</span>
</div>

<!-- Product Detail -->
<div class="container bgwhite p-t-35 p-b-80">
	<div class="flex-w flex-sb">
		<div class="w-size13 p-t-30 respon5">
			<div class="wrap-slick3 flex-sb flex-w">
				<div class="wrap-slick3-dots"></div>
				<div class="slick3">
					{% for item in Images %}
						<div class="item-slick3" data-thumb="{{item}}">
							<div class="wrap-pic-w">
								<img src="{{item}}" alt="IMG-PRODUCT">
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>

		<div class="w-size14 p-t-30 respon5">
			<h4 class="product-detail-name m-text16 p-b-13">
				{{ThisProduct.title}}
			</h4>

			<span class="m-text17" style="color: rgb(255, 0, 0);">
				تومان {{ThisProduct.price|currency}}
			</span>

			<!--  -->
			<div class="p-t-33 p-b-60">
				<div class="flex-r-m flex-w p-t-10">
					<div class="w-size16 flex-m flex-w">
						<form>
							{% csrf_token %}
							<div class="flex-w bo5 of-hidden m-r-22 m-t-10 m-b-10">
								<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
								</button>

								<input class="size8 m-text18 t-center num-product" type="number" name="num-product" value="1" id="count">

								<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
									<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
								</button>
							</div>

							<div class="btn-addcart-product-detail size9 trans-0-4 m-t-10 m-b-10">
								<!-- Button -->
								<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" type="submit" id="send-form">
									اضافه به سبد خرید
								</button>
							</div>
						</form>
					</div>
				</div>
			</div>

			<!--  -->
			{% if ThisProduct.description|length > 0 %}
			<div class="wrap-dropdown-content bo6 p-t-15 p-b-14 active-dropdown-content">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					توضیحات محصول
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>

				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">
						{{ThisProduct.description}}
					</p>
				</div>
			</div>
			{% endif %}

			<div class="wrap-dropdown-content bo7 p-t-15 p-b-14">
				<h5 class="js-toggle-dropdown-content flex-sb-m cs-pointer m-text19 color0-hov trans-0-4">
					ویژگی محصول
					<i class="down-mark fs-12 color1 fa fa-minus dis-none" aria-hidden="true"></i>
					<i class="up-mark fs-12 color1 fa fa-plus" aria-hidden="true"></i>
				</h5>

				<div class="dropdown-content dis-none p-t-15 p-b-23">
					<p class="s-text8">
						<ul>
							{% for item in ThisProduct.attributes.attributes %}
								<li>
									{{item.title}} : {{item.value}}
								</li>
							{% endfor %}
						</ul>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Relate Product -->
<section class="relateproduct bgwhite p-t-45 p-b-138">
	<div class="container">
		<div class="sec-title p-b-60">
			<h3 class="m-text5 t-center">
				محصولات مشابه
			</h3>
		</div>

		<!-- Slide2 -->
		<div class="wrap-slick2">
			<div class="slick2">
				{% for item in Top_Products %}
					<div class="item-slick2 p-l-15 p-r-15">
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
								<img src="{{item.top_image}}" alt="IMG-PRODUCT"  width="250" height="250">

								<div class="block2-overlay trans-0-4">
									<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
										<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
										<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
									</a>

									<div class="block2-btn-addcart w-size1 trans-0-4">
										<!-- Button -->
										<a href="{{item.get_url}}" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
											مشاهده
										</a>
									</div>
								</div>
							</div>

							<div class="block2-txt p-t-20">
								<a href="{{item.get_url}}" class="block2-name dis-block s-text3 p-b-5">
									{{item.title}}
								</a>

								<span class="block2-price m-text6 p-r-5">
									تومان {{item.price|currency}}
								</span>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>

	</div>
</section>

{% block footer %}
	{% include "parents/footer.html" %}
{% endblock %}

<!-- Ajax -->
<script text="javascripts">
	$("#send-form").on("click", function (e) {
		e.preventDefault();
		var  this_id = '{{ThisProduct.id|safe}}';
		var  this_count = $('#count').val();
		$.ajax(
			{
				type: 'POST',
				url: '{% url "shop:ajax_add_to_card" %}',
				data: {
					this_product: this_id,
					this_count: this_count,
					csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
				},
				success: function (json, status, xhr) {
					if (xhr.status == 200) {
						alert('محصول مورد نظر به سبد خرید شما اضافه شد.');
					}
				},
				error: function (xhr) {
					if (xhr.status == 401)
					{
						alert('لطفا وارد حساب کاربری خود شوید.');
						var redirectURL = '{% url "shop:sign_in_page" %}';
						location.replace(redirectURL);
					}
					else
					{
						alert('خطایی رخ داده است.');
					}
					console.log(xhr.status + ": " + xhr.responseText);
				}
			}
		);  
	})
</script>

<!--===============================================================================================-->
	<script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
<!--===============================================================================================-->
	<script type="text/javascript">
		//$('.block2-btn-addcart').each(function(){
		//	var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
		//	$(this).on('click', function(){
		//		swal(nameProduct, "is added to cart !", "success");
		//	});
		//});

		//$('.block2-btn-addwishlist').each(function(){
		//	var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
		//	$(this).on('click', function(){
		//		swal(nameProduct, "is added to wishlist !", "success");
		//	});
		//});
	</script>
<!--===============================================================================================-->

</body>
</html>